// raise.ts — AN ADVISORY OPENS A QUESTION INSTEAD OF PRINTING ONE.
//
// THE FINDING THIS EXISTS FOR. Suspicions were STORED in the journal but GENERATED by the
// advisory layer, and only one generator was ever wired: `observed.ts`. `redundancy`,
// `verify`, `novelty`, `drift`, `why-lint`, `conventions`, `atlas` and `contracts` wrote
// zero — and every one of them already FORMS a suspicion and then throws it away by
// printing it. Verbatim, from the code that shipped:
//   · redundancy — "the two spellings ALREADY disagree — either the difference is
//     intended (say so), or one side drifted." That is a conjecture with two candidates.
//   · verify/never-red — "green every run, never once red, no recorded refutation."
//   · verify/refutations — "never observed failing."
//   · verify/kinds — "this claim could convict us for improving."
// Each is a question with an obvious first hypothesis and an obvious discriminating test,
// scrolled past once per run forever. This module is the one call that turns any of them
// into an entry that outlives the run.
//
// ── THE DESIGN PROBLEM, AND IT IS THE WHOLE MODULE ────────────────────────────────────
//
// `observed` dedupes on a LABEL THE CALLER SUPPLIES: the project spells "CO2 range, low"
// the same way twice, so the label is what holds still while the number moves. An advisory
// has nobody to ask. It must derive a stable identity FROM THE FINDING, and there are two
// ways to get that wrong, both fatal and in opposite directions:
//
//   TOO VOLATILE → every run opens a new question and `--open` is noise within a week.
//   TOO COARSE   → two genuinely different findings collapse and the second is SWALLOWED,
//                  silently, which is worse than never having raised it.
//
// The rule that resolves it: THE KEY IS THE FINDING'S SUBJECT — the addressable thing a
// reader would go and look at — AND NOTHING ELSE. Not its magnitude, not its rank, not its
// position in a file. Concretely, what is deliberately EXCLUDED and why:
//
//   · A SCORE. The redundancy score is the most volatile number in the report, and not
//     for the reason it looks: `df` (how many sites hold a token) is computed over the
//     WHOLE TREE, so adding one unrelated file re-ranks every pair in the repo. A key
//     containing it mints a new question on an edit that did not touch either site.
//   · A COUNT. "green for 14 runs" changes every run by construction. It is the most
//     tempting field to include, because it is what makes the finding feel urgent.
//   · A LINE NUMBER. Inserting a line above a site moves it without changing it. This
//     repo already made that call once, for the same reason, in a different place:
//     `cli.ts` strips `data-line` before comparing graph.json, because "line numbers are
//     a navigation aid, never structure". A site's identity is `file#kind:name`.
//
// AND ONE PLACE THE NAME ITSELF IS VOLATILE, which the first draft missed: an alternation
// site is named `alternation@<line>`, so the line is INSIDE the name. Stripping the suffix
// would fuse every alternation in a file into one key — the coarse failure. So a
// positional name is replaced by a digest of the site's own token set: two alternations in
// one file stay distinct, and moving either one does not re-key it. See `stableSiteName`.
//
// ── FIRST-RUN VOLUME, WHICH IS THE MOST LIKELY WAY THIS DIES ──────────────────────────
//
// A large repo's first run must not open two hundred questions. Three layers, because
// each catches a case the others do not:
//
//   1. OPT-IN (`--raise`). Raising WRITES. An advisory that silently mutates the decision
//      journal as a side effect of a read-only report is a surprise, and a surprising
//      write is how a mechanism gets switched off wholesale rather than tuned. It also
//      keeps pre-commit hooks — which run `verify` for its printed output — from raising.
//   2. THE ADVISORY'S OWN FLOOR. Only findings the advisory already SHOWS may raise.
//      This is doing the most work: `redundancy --all` drops the score floor to 0 to
//      expose the tail, and raising must ignore that and use the DEFAULT floor. The
//      refutation advisory prints its per-invariant list only once a project has declared
//      its first refutation, so on a project with none it raises nothing at all.
//   3. A HARD CAP PER RUN, AND IT SAYS WHAT IT WITHHELD. The floor is a precision knob and
//      a repo can still sit above it three hundred times. The cap is the bound that does
//      not depend on tuning. Silence about the remainder was never an option: a truncated
//      list that looks complete is the defect this whole harness hunts.
//
// The cap is per RUN, not per advisory, so the promise a reader gets is a simple one —
// one `--raise` opens at most N questions, whatever it was pointed at.
//
// AND THE CAP IS SPENT ROUND-ROBIN ACROSS ADVISORIES, which the first dogfood run forced.
// Strict priority order was the obvious design and it was wrong: on planetizer, `verify`
// offered 14 never-red findings and 3 warned-kind ones, and the withheld line read
// `never-red 9 · warned-kind 3` — every warned-kind question sitting behind twelve others,
// on a repo where the project itself had declared that kind the suspect one. A detector
// that never speaks is a detector nobody wired. Round-robin bounds starvation at one round
// per advisory, and the caller's ordering still decides who goes first within a round.
//
// ── A FINDING THAT DISAPPEARS DOES NOT CLOSE ITS QUESTION ─────────────────────────────
//
// Derive one spelling from the other and the redundancy pair stops being reported — but
// its question stays open until somebody says what happened. That is the same rule
// `observed` follows when a metric wanders back inside its band, and for the same reason:
// the absence of a symptom is not an explanation, and auto-closing would delete the entry
// from `--open` in precisely the case where nobody was looking. `coherence resolved` when
// you know the answer; `coherence dismiss` when you have decided not to find out.
//
// IT GATES NOTHING. Every path here returns a report and no exit code.
import { appendDecision, resolve, type DecisionRecord } from "./decisions.ts";
import type { Config } from "./types.ts";

/** One suspicion an advisory formed, ready to become a journal entry. */
export interface Finding {
  /** The advisory that formed it. Namespaces the key, so two detectors cannot collide. */
  advisory: string;
  /**
   * THE SUBJECT — the addressable thing this finding is about, and nothing else. Derived
   * by the advisory from what it is looking at, never from what it measured. Anything in
   * here that can change without the finding changing is a bug that shows up a week later
   * as a journal full of near-duplicates.
   */
  subject: string;
  /** The observation, worded to stay TRUE after somebody explains it. Becomes `chose`.
   *  Free to carry volatile detail (line numbers, run counts, a score) — identity comes
   *  from `subject`, not from this, which is the entire point of separating them. */
  observation: string;
  /** Why it is worth a reader's attention. Becomes `because`. */
  because?: string;
  /** Candidate explanations. `[instrument]` is added at the write if none reads as doubt
   *  of the apparatus — so an advisory that forgets its own detector could be wrong still
   *  ships a conjecture that says so. */
  couldBe?: string[];
  /** The test that separates the candidates. Required — without it the entry is a
   *  complaint, and an advisory-generated complaint is a nag with a UUID. */
  discriminatedBy: string;
  files?: string[];
}

/** `<advisory>:<subject>` — readable rather than hashed, so somebody debugging a
 *  duplicate can grep the journal and SEE which half of the key moved. */
export const findingKey = (f: Pick<Finding, "advisory" | "subject">): string => `${f.advisory}:${f.subject}`;

/** THE CAP, per run rather than per advisory. Three is chosen against the thing it has to
 *  survive — a person's willingness to work a queue. A run that hands back three questions
 *  is a run whose output can be acted on before the next one; ten is a backlog on arrival,
 *  and a backlog is indistinguishable from noise to the reader who has to triage it. It is
 *  a floor on ATTENTION, not on precision, so it does not move when a detector improves. */
export const RAISE_CAP = 3;

export interface RaiseOpts {
  /** `--raise`. Default FALSE: writing is a decision, never a side effect of reporting. */
  enabled?: boolean;
  cap?: number;
  agent?: string; job?: string; session?: string; now?: string;
}

export interface RaiseReport {
  enabled: boolean;
  cap: number;
  /** How many findings the advisory offered — everything above its own floor. */
  considered: number;
  /** No prior entry: the questions that do not exist yet. `opened` ⊆ this. */
  fresh: Finding[];
  /** Written this run. Empty when raising is off. */
  opened: { finding: Finding; rec: DecisionRecord }[];
  /** Fresh, over the cap. NEVER silent — `formatRaise` names the count per advisory. */
  withheld: Finding[];
  /** The dedupe working: a question about this subject is already open. */
  alreadyOpen: { finding: Finding; rec: DecisionRecord }[];
  /** Answered, or retired unanswered. Either way: quiet, and it stays quiet. */
  settled: { finding: Finding; rec: DecisionRecord; how: "resolved" | "dismissed" }[];
  /** Writes that threw. Advisory or not, a lost entry is reported, never swallowed. */
  failed: number;
}

export interface RaisePrior {
  open?: DecisionRecord;
  settled?: { rec: DecisionRecord; how: "resolved" | "dismissed" };
}

/** What the journal already holds, indexed by derived key — the read half of the dedupe.
 *
 *  A RETRACTED conjecture is indexed as NEITHER, exactly as `observed.priorFor` treats
 *  one: a retraction claims the observation was never real, so if the detector keeps
 *  producing it, that claim is the thing that deserves re-examination. The question is
 *  allowed to be asked again.
 *
 *  A DISMISSED one is indexed as settled, and that is the difference between a mechanism
 *  people keep and one they turn off. `dismiss` has to mean permanently. */
export function priorsByFinding(records: DecisionRecord[]): Map<string, RaisePrior> {
  const { open, resolved, dismissed } = resolve(records);
  const out = new Map<string, RaisePrior>();
  const at = (r: DecisionRecord) => r.at;
  for (const r of [...open].sort((a, b) => at(a).localeCompare(at(b)))) {
    if (r.finding) out.set(r.finding, { ...(out.get(r.finding) ?? {}), open: r });
  }
  const settlements = [
    ...resolved.map(({ rec }) => ({ rec, how: "resolved" as const })),
    ...dismissed.map(({ rec }) => ({ rec, how: "dismissed" as const })),
  ].sort((a, b) => at(a.rec).localeCompare(at(b.rec)));
  for (const s of settlements) {
    if (s.rec.finding) out.set(s.rec.finding, { ...(out.get(s.rec.finding) ?? {}), settled: s });
  }
  return out;
}

/**
 * THE ONE ENTRY POINT. Bucket every finding against the journal, write at most `cap` of
 * the ones nobody has asked about yet, and hand back what happened to all of them.
 *
 * It takes the whole batch rather than one finding at a time for two reasons, and the
 * second is the load-bearing one: the journal is read ONCE instead of per finding
 * (`observed` re-reads per call, which is right for one row a run and wrong for forty),
 * and the cap cannot report what it withheld unless it can see the whole set.
 */
export function raiseFindings(
  cfg: Config, records: DecisionRecord[], findings: Finding[], opts: RaiseOpts = {},
): RaiseReport {
  const cap = opts.cap ?? RAISE_CAP;
  const enabled = !!opts.enabled;
  const priors = priorsByFinding(records);
  const report: RaiseReport = {
    enabled, cap, considered: findings.length,
    fresh: [], opened: [], withheld: [], alreadyOpen: [], settled: [], failed: 0,
  };

  for (const f of findings) {
    const prior = priors.get(findingKey(f));
    if (prior?.open) { report.alreadyOpen.push({ finding: f, rec: prior.open }); continue; }
    if (prior?.settled) { report.settled.push({ finding: f, ...prior.settled }); continue; }
    report.fresh.push(f);
  }
  // Reordered here rather than at the write, so `withheld` (= everything past the cap) is
  // the exact complement of what was opened and the report cannot lie about either.
  report.fresh = interleaveByAdvisory(report.fresh);

  if (!enabled) return report;

  for (const f of report.fresh) {
    if (report.opened.length >= cap) { report.withheld.push(f); continue; }
    try {
      const rec = appendDecision(cfg, {
        kind: "conjecture",
        chose: f.observation,
        because: f.because ?? "",
        couldBe: f.couldBe ?? [],
        discriminatedBy: f.discriminatedBy,
        finding: findingKey(f),
        files: f.files,
        agent: opts.agent, job: opts.job, session: opts.session, now: opts.now,
      });
      report.opened.push({ finding: f, rec });
    } catch { report.failed++; }
  }
  return report;
}

/** Deal the findings out round-robin by advisory, preserving each advisory's own ranking
 *  within its turn. One detector cannot then consume a whole run's cap and silence the
 *  others — see the module header for the run that made this necessary. */
export function interleaveByAdvisory(fs: Finding[]): Finding[] {
  const lanes = new Map<string, Finding[]>();
  for (const f of fs) (lanes.get(f.advisory) ?? lanes.set(f.advisory, []).get(f.advisory)!).push(f);
  const out: Finding[] = [];
  const all = [...lanes.values()];
  for (let i = 0; out.length < fs.length; i++) for (const lane of all) if (i < lane.length) out.push(lane[i]);
  return out;
}

/** Group a list of findings by the advisory that formed it, in first-seen order — so the
 *  withheld line can say WHICH detector is starving rather than only how many. */
function byAdvisory(fs: Finding[]): string {
  const n = new Map<string, number>();
  for (const f of fs) n.set(f.advisory, (n.get(f.advisory) ?? 0) + 1);
  return [...n].map(([a, c]) => `${a} ${c}`).join(" · ");
}

/** What the advisory prints. Short: this runs at the end of a report that is already
 *  long, and the lines that matter are the ids and the two commands that retire them.
 *
 *  WITH RAISING OFF IT STILL SPEAKS, and that is not decoration — it is the only way
 *  anyone learns the verb exists. One line, and only when there is something to raise:
 *  a repo whose findings are all already open or already settled says nothing at all,
 *  because a permanent line is furniture and furniture is what the eye skips. */
export function formatRaise(r: RaiseReport): string[] {
  const known = r.alreadyOpen.length + r.settled.length;
  const knownTail = known
    ? `  (${r.alreadyOpen.length} already open · ${r.settled.length} already settled)`
    : "";
  if (!r.enabled) {
    if (!r.fresh.length) {
      // Everything here has been asked. Worth one line — it is the dedupe reporting that
      // it worked, and the alternative reads as the advisory having found nothing.
      return known ? [`  RAISE — every finding above is already in the journal${knownTail.trimStart()}.`] : [];
    }
    return [
      `  RAISE — ${r.fresh.length} of these ${r.considered} finding(s) have never been asked about.`
      + `  \`--raise\` opens up to ${r.cap} as questions in .coherence/decisions/.`,
      ...(known ? [knownTail] : []),
    ];
  }

  const out: string[] = [];
  // An EXPLICIT `--raise` that raised nothing must say so. Silence would be ambiguous
  // between "there was nothing above the floor" and "the flag did not take" — the same
  // ambiguity `decisions --open` refuses. Unasked-for silence is furniture; asked-for
  // silence is a bug report waiting to happen.
  if (!r.considered) return ["  RAISE — nothing to raise: no advisory here produced a finding above its own floor."];
  out.push(`  RAISE — ${r.opened.length} question(s) opened in the decision journal`
    + ` (${r.considered} finding(s) considered${known ? `, ${r.alreadyOpen.length} already open, ${r.settled.length} already settled` : ""})`);
  for (const { finding, rec } of r.opened) out.push(`    ${rec.id}  ${findingKey(finding)}`);
  if (r.withheld.length) {
    out.push(`    WITHHELD ${r.withheld.length} more — the cap is ${r.cap} per run (${byAdvisory(r.withheld)}).`);
    out.push("    They are not lost and they are not recorded: settle the ones above and re-run.");
  }
  if (r.failed) out.push(`    ${r.failed} write(s) FAILED — the journal did not take them. Check .coherence/ is writable.`);
  if (r.opened.length) {
    out.push("    settle one:   coherence resolved <id> --because \"<what the test showed>\" --as \"<which candidate won>\"");
    out.push("    or retire it: coherence dismiss  <id> --because \"<why this is not worth chasing>\"");
  }
  return out;
}
