// render-claude.ts — Graph → the GENERATED block of a project's CLAUDE.md.
import { join } from "node:path";
import type { Config } from "./types.ts";
//
// The sibling of render-overview.ts (AGENTS.md). Where AGENTS.md is a standalone
// generated file, CLAUDE.md is two-zone: an authored prose document (why-essays,
// conventions, doctrine — the WHY, which the graph cannot derive) with ONE fenced
// block this function owns. We regenerate only the fenced block; cli.ts splices it
// in between the fence markers and preserves everything outside (see spliceBlock).
//
// HONEST SCOPE — generate only what the graph actually KNOWS:
//   - the component/directory map: each component dir + its one-line spec intent + its files
//   - the invariants → chokepoint(anchor) → oracle table, parsed from boundary claims
//   - derivable counts (components, files, symbols, boundary claims)
//
// PARTIAL: per-file prose is emitted WHEN PRESENT — a file's top-of-file docblock
// `prose` (the part before any `@why`) becomes a one-line role beside the filename.
// A file without a docblock appears as a bare label, same as before. This lets the
// rich per-file one-liners that CLAUDE.md trees often hand-maintain move into the
// docblocks coherence already reads, eliminating a hand-maintained duplicate without
// requiring uniform coverage to do so. The `@why` half stays out — the generated
// block surfaces ROLE (the WHAT), not rationale (the WHY).
//
// DELIBERATELY NOT GENERATED (stays authored, outside the fences):
//   - all the WHY: design-principle essays, conventions, vocabulary, tech-stack notes.
import type { Graph } from "./types.ts";
import { parseBoundary } from "./boundary.ts";

export const CLAUDE_BEGIN = "<!-- coherence:begin -->";
export const CLAUDE_END = "<!-- coherence:end -->";

export function renderClaude(graph: Graph, stamp: string): string {
  const comps = graph.nodes.filter((n) => n.kind === "component");
  const childrenOf = (pid: string) => graph.nodes.filter((n) => n.parent === pid && n.kind === "file");
  const counts = graph.nodes.reduce<Record<string, number>>((a, n) => ((a[n.kind] = (a[n.kind] ?? 0) + 1), a), {});

  // collect every boundary claim across components for the invariants table
  type Boundary = { comp: string; name: string; chokepoint: string; oracle: string; kind: string; refuted: boolean };
  const boundaries: Boundary[] = [];
  let anyKind = false, anyRefutation = false;
  for (const c of comps) {
    // `## refutations` lines are keyed `<invariant>: <what was broken> -> <what was seen>`.
    const refuted = new Set((c.refutations ?? []).map((r) => r.split(":")[0].trim()));
    if (refuted.size) anyRefutation = true;
    for (const claim of c.claims ?? []) {
      const b = parseBoundary(claim);
      if (!b) continue;
      const kind = c.claimKinds?.[claim] ?? "";
      if (kind) anyKind = true;
      boundaries.push({ comp: c.label, name: b.inv, chokepoint: b.chokepoint, oracle: b.oracle || "—", kind, refuted: refuted.has(b.inv) });
    }
  }

  const md: string[] = [];
  md.push(CLAUDE_BEGIN);
  md.push("<!-- GENERATED by `coherence claude` from the spec+code graph. Do not edit by hand —");
  md.push("     edit the *.spec.md files and re-run. Everything OUTSIDE these markers is authored prose. -->");
  md.push("");
  md.push(`_Derived from ${counts.component ?? 0} components · ${counts.file ?? 0} files · ${counts.symbol ?? 0} symbols · ${boundaries.length} boundary claims._`);
  md.push("");

  // ── component / directory map ──
  md.push("## Component map (derived)", "");
  md.push("> Each component directory, its spec intent (one line), and its files. Per-file");
  md.push("> roles are authored elsewhere — the graph only knows component-level intent.", "");
  for (const c of comps) {
    const path = c.id.slice(2); // strip "c:"
    md.push(`### ${c.label} \`${path === "." ? "/" : path}\``);
    if (c.sub) md.push(c.sub);
    const files = childrenOf(c.id);
    if (files.length) {
      // Pivot: if NO file has prose, render the compact one-line list (old behavior,
      // legible at-a-glance for component dirs full of organizational sub-modules).
      // If ANY file has prose, render a per-file bullet list so the prose actually
      // shows; files without prose appear as bare-label rows so the list stays full.
      const any = files.some((f) => f.prose);
      if (!any) {
        md.push("", `_files:_ ${files.map((f) => `\`${f.label}\``).join(", ")}`);
      } else {
        md.push("", "_files:_");
        for (const f of files) {
          const one = (f.prose ?? "").split(/\r?\n/)[0].trim();
          md.push(one ? `- \`${f.label}\` — ${esc(one)}` : `- \`${f.label}\``);
        }
      }
    }
    md.push("");
  }

  // ── invariants → chokepoint → oracle table ──
  md.push("## Invariants → chokepoint → oracle (derived)", "");
  if (boundaries.length) {
    md.push("> Each named invariant, the chokepoint symbol that enforces it, and the oracle");
    md.push("> (test or guard) that asserts it holds. Parsed from the `boundary` claims in the specs.", "");
    // The KIND and REFUTED columns appear only for projects that use those features, so a
    // spec tree that declares neither renders exactly the table it rendered before. They are
    // here rather than in verify's transient output because this is the file a fresh agent
    // reads: "this invariant is `measured`, so it could convict us for improving" and
    // "nobody has ever watched this one fail" are the two facts that do not survive a
    // context boundary on their own.
    const cols = ["Invariant", "Component", "Chokepoint", "Oracle"];
    if (anyKind) cols.push("Kind");
    if (anyRefutation) cols.push("Refuted?");
    md.push(`| ${cols.join(" | ")} |`);
    md.push(`| ${cols.map(() => "---").join(" | ")} |`);
    for (const b of boundaries) {
      const row = [esc(b.name), esc(b.comp), `\`${esc(b.chokepoint)}\``, b.oracle === "—" ? "—" : `\`${esc(b.oracle)}\``];
      if (anyKind) row.push(b.kind ? `\`${esc(b.kind)}\`` : "—");
      if (anyRefutation) row.push(b.refuted ? "observed" : "—");
      md.push(`| ${row.join(" | ")} |`);
    }
    if (anyRefutation) md.push("", "_\"Refuted?\" = someone broke the chokepoint and watched this oracle go red. A `—` is a to-do, not an accusation._");
    md.push("");
  } else {
    md.push("_No `boundary` claims declared in the specs._", "");
  }

  md.push(`<sub>Generated at ${stamp}.</sub>`);
  md.push(CLAUDE_END);
  return md.join("\n");
}

const esc = (s: unknown) => String(s).replace(/\|/g, "\\|").replace(/\n+/g, " ");

/**
 * Splice a freshly-generated block into existing CLAUDE.md content between the
 * fence markers, preserving everything outside them. Returns null if the markers
 * are absent (the caller must NOT clobber a file that hasn't opted in).
 */
export function spliceBlock(existing: string, block: string): string | null {
  const i = existing.indexOf(CLAUDE_BEGIN);
  const j = existing.indexOf(CLAUDE_END);
  if (i < 0 || j < 0 || j < i) return null;
  return existing.slice(0, i) + block + existing.slice(j + CLAUDE_END.length);
}

/** Extract the current fenced block (markers inclusive) from CLAUDE.md, or null. */
export function extractBlock(existing: string): string | null {
  const i = existing.indexOf(CLAUDE_BEGIN);
  const j = existing.indexOf(CLAUDE_END);
  if (i < 0 || j < 0 || j < i) return null;
  return existing.slice(i, j + CLAUDE_END.length);
}

/** Resolve the CLAUDE.md path the splicer writes to. `cfg.claudeMdPath` defaults
 *  to `CLAUDE.md` (sibling of the specs); a `../`-relative path escapes cfg.root,
 *  for the case where the authored CLAUDE.md lives at a repo root above a
 *  sub-package whose coherence config is nested. Coherence still operates on
 *  cfg.root; only the splice target moves. */
export function resolveClaudeMdPath(cfg: Config): string {
  return join(cfg.root, cfg.claudeMdPath ?? "CLAUDE.md");
}
