// render-claude.ts — Graph → the GENERATED block of a project's CLAUDE.md.
//
// The sibling of render-overview.ts (AGENTS.md). Where AGENTS.md is a standalone
// generated file, CLAUDE.md is two-zone: an authored prose document (why-essays,
// conventions, doctrine — the WHY, which the graph cannot derive) with ONE fenced
// block this function owns. We regenerate only the fenced block; cli.ts splices it
// in between the fence markers and preserves everything outside (see spliceBlock).
//
// HONEST SCOPE — generate only what the graph actually KNOWS:
//   - the component/directory map: each component dir + its one-line spec intent + its files
//   - the invariants → chokepoint(anchor) → oracle table, parsed from boundary claims
//   - derivable counts (components, files, symbols, boundary claims)
//
// DELIBERATELY NOT GENERATED (stays authored, outside the fences):
//   - per-FILE prose roles. The graph carries COMPONENT-level `intent` (spec `sub`)
//     and FILE-level `prose`/`why` only when a file happens to have a docblock — it
//     does NOT carry a curated one-line "what this file is for" for every file. So we
//     emit the bare file list per component and let the rich per-file one-liners (the
//     kind CLAUDE.md hand-maintains in its "Project structure" tree) stay AUTHORED.
//   - all the WHY: design-principle essays, conventions, vocabulary, tech-stack notes.
import type { Graph, GraphNode } from "./types.ts";

export const CLAUDE_BEGIN = "<!-- coherence:begin -->";
export const CLAUDE_END = "<!-- coherence:end -->";

/** Parse a `boundary "<name>" at <chokepoint> [via test "<oracle>"]` claim. Mirrors verify.ts. */
const BOUNDARY_RE = /^boundary\s+"([^"]+)"\s+at\s+(\S+)(?:\s+via test\s+"([^"]+)")?$/;

export function renderClaude(graph: Graph, stamp: string): string {
  const comps = graph.nodes.filter((n) => n.kind === "component");
  const childrenOf = (pid: string) => graph.nodes.filter((n) => n.parent === pid && n.kind === "file");
  const counts = graph.nodes.reduce<Record<string, number>>((a, n) => ((a[n.kind] = (a[n.kind] ?? 0) + 1), a), {});

  // collect every boundary claim across components for the invariants table
  type Boundary = { comp: string; name: string; chokepoint: string; oracle: string };
  const boundaries: Boundary[] = [];
  for (const c of comps) {
    for (const claim of c.claims ?? []) {
      const m = BOUNDARY_RE.exec(claim);
      if (m) boundaries.push({ comp: c.label, name: m[1], chokepoint: m[2], oracle: m[3] ?? "—" });
    }
  }

  const md: string[] = [];
  md.push(CLAUDE_BEGIN);
  md.push("<!-- GENERATED by `coherence claude` from the spec+code graph. Do not edit by hand —");
  md.push("     edit the *.spec.md files and re-run. Everything OUTSIDE these markers is authored prose. -->");
  md.push("");
  md.push(`_Derived from ${counts.component ?? 0} components · ${counts.file ?? 0} files · ${counts.symbol ?? 0} symbols · ${boundaries.length} boundary claims._`);
  md.push("");

  // ── component / directory map ──
  md.push("## Component map (derived)", "");
  md.push("> Each component directory, its spec intent (one line), and its files. Per-file");
  md.push("> roles are authored elsewhere — the graph only knows component-level intent.", "");
  for (const c of comps) {
    const path = c.id.slice(2); // strip "c:"
    md.push(`### ${c.label} \`${path === "." ? "/" : path}\``);
    if (c.sub) md.push(c.sub);
    const files = childrenOf(c.id);
    if (files.length) {
      md.push("", `_files:_ ${files.map((f) => `\`${f.label}\``).join(", ")}`);
    }
    md.push("");
  }

  // ── invariants → chokepoint → oracle table ──
  md.push("## Invariants → chokepoint → oracle (derived)", "");
  if (boundaries.length) {
    md.push("> Each named invariant, the chokepoint symbol that enforces it, and the totality");
    md.push("> oracle (test) that asserts it holds. Parsed from the `boundary` claims in the specs.", "");
    md.push("| Invariant | Component | Chokepoint | Oracle |");
    md.push("| --- | --- | --- | --- |");
    for (const b of boundaries) {
      md.push(`| ${esc(b.name)} | ${esc(b.comp)} | \`${esc(b.chokepoint)}\` | ${b.oracle === "—" ? "—" : `\`${esc(b.oracle)}\``} |`);
    }
    md.push("");
  } else {
    md.push("_No `boundary` claims declared in the specs._", "");
  }

  md.push(`<sub>Generated at ${stamp}.</sub>`);
  md.push(CLAUDE_END);
  return md.join("\n");
}

const esc = (s: unknown) => String(s).replace(/\|/g, "\\|").replace(/\n+/g, " ");

/**
 * Splice a freshly-generated block into existing CLAUDE.md content between the
 * fence markers, preserving everything outside them. Returns null if the markers
 * are absent (the caller must NOT clobber a file that hasn't opted in).
 */
export function spliceBlock(existing: string, block: string): string | null {
  const i = existing.indexOf(CLAUDE_BEGIN);
  const j = existing.indexOf(CLAUDE_END);
  if (i < 0 || j < 0 || j < i) return null;
  return existing.slice(0, i) + block + existing.slice(j + CLAUDE_END.length);
}

/** Extract the current fenced block (markers inclusive) from CLAUDE.md, or null. */
export function extractBlock(existing: string): string | null {
  const i = existing.indexOf(CLAUDE_BEGIN);
  const j = existing.indexOf(CLAUDE_END);
  if (i < 0 || j < 0 || j < i) return null;
  return existing.slice(i, j + CLAUDE_END.length);
}
